// ============================================================
// Sweet Flour — Campaign Roadmap 2026
// Design: Warm Artisan Editorial
// Colors: Chocolate Brown #3D1A0A | Sky Blue #A8DDE9 | Cream #FBF7F2
// Fonts: Playfair Display (headings) + DM Sans (body)
// ============================================================

export type CampaignStatus = 'active' | 'in-production' | 'planned' | 'paused';
export type CampaignType = 'evergreen' | 'seasonal' | 'corporate' | 'remarketing';
export type CampaignChannel = 'meta' | 'google' | 'both';
export type CampaignPriority = 'high' | 'medium' | 'low';

export interface ProductionTask {
  id: string;
  task: string;
  owner: 'design' | 'media' | 'client' | 'production';
  dueWeeks: number;
  status: 'pending' | 'in-progress' | 'done';
}

export interface Campaign {
  id: string;
  name: string;
  type: CampaignType;
  status: CampaignStatus;
  priority: CampaignPriority;
  channel: CampaignChannel;
  startDate: string;
  endDate: string;
  products: string[];
  productLabels: string[];
  platforms: string[];
  goal: string;
  targetAudience: string;
  location: string;
  adCopy: string;
  creativeIdeas: string;
  assets: string[];
  productionTasks: ProductionTask[];
  benchmark: {
    outboundCTR: number;
    roas: number;
    cpm: number;
    frequency: number;
    budget: string;
  };
  monthlyBudget: string;
  notes: string;
  seasonalColor: string;
  emoji: string;
  quarter: number;
  month: number;
  endMonth: number;
  year: number;
  dataInsight?: string;
  ksNotes?: string;
}

export const campaigns: Campaign[] = [
  // ─────────────────────────────────────────────
  // ALWAYS-ON / EVERGREEN CAMPAIGNS
  // ─────────────────────────────────────────────
  {
    id: 'ev-cookies-canada',
    name: 'PMax | Cookies | Canada',
    type: 'evergreen',
    status: 'active',
    priority: 'high',
    channel: 'google',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    products: ['cookies', 'gift-boxes'],
    productLabels: ['Cookies', 'Cookie Gift Boxes', 'Cookie Cakes'],
    platforms: ['Google Performance Max'],
    goal: 'Drive year-round cookie sales across Canada via Google PMax — Max Conversion Value',
    targetAudience: 'Canada-wide cookie buyers, gift-givers, celebration occasions',
    location: 'Canada',
    adCopy: '"Make any day sweeter." / "Fresh-baked cookies delivered across Canada."',
    creativeIdeas: 'Product photography, lifestyle gifting scenes, seasonal cookie variety shots',
    assets: ['Product photography', 'Lifestyle shots', 'Google asset group images', 'Headlines + descriptions'],
    productionTasks: [
      { id: 'pmax-ck-1', task: 'Refresh PMax asset group — new product photos', owner: 'production', dueWeeks: 2, status: 'in-progress' },
      { id: 'pmax-ck-2', task: 'Add 5 new headline variants to asset group', owner: 'media', dueWeeks: 1, status: 'pending' },
      { id: 'pmax-ck-3', task: 'Exclude 98% of products flagged — review product feed', owner: 'media', dueWeeks: 1, status: 'pending' },
      { id: 'pmax-ck-4', task: 'Review search term report for negative keywords', owner: 'media', dueWeeks: 1, status: 'pending' },
    ],
    benchmark: { outboundCTR: 1.73, roas: 5.20, cpm: 10.32, frequency: 1.0, budget: 'CA$82/day (~CA$2,460/mo)' },
    monthlyBudget: 'CA$2,460/mo (CA$82/day)',
    notes: 'Top Google campaign by spend. Conv. value/cost: 5.20. CTR 1.73%. 96% products excluded — fix product feed urgently.',
    seasonalColor: '#2B6CB0',
    emoji: '',
    quarter: 1,
    month: 1,
    endMonth: 12,
    year: 2026,
    dataInsight: 'Apr 1–7: 15,284 impressions | 264 clicks | 1.73% CTR | 12 conversions | ROAS 5.20x | Top performer — 40% of Google budget allocation',
  },
  {
    id: 'ev-cupcakes-gta',
    name: 'PMax | Cupcakes | GTA',
    type: 'evergreen',
    status: 'active',
    priority: 'high',
    channel: 'google',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    products: ['cupcakes'],
    productLabels: ['Cupcakes', 'Cupcake Gift Boxes', 'Birthday Cupcakes'],
    platforms: ['Google Performance Max'],
    goal: 'Drive cupcake sales in GTA — Max Conversion Value. Campaign is Limited by Target — budget needs review.',
    targetAudience: 'GTA residents 25–55, birthday gift-givers, event planners',
    location: 'GTA (Brampton, Markham, Mississauga, Oakville)',
    adCopy: '"Celebrate with fresh-baked cupcakes." / "Toronto\'s favourite cupcake delivery."',
    creativeIdeas: 'Cupcake variety shots, birthday occasion creative, GTA delivery messaging',
    assets: ['Cupcake product photography', 'Birthday occasion lifestyle', 'Google asset group images'],
    productionTasks: [
      { id: 'pmax-cup-1', task: 'Review "Limited by Target" — adjust tROAS or budget', owner: 'media', dueWeeks: 1, status: 'in-progress' },
      { id: 'pmax-cup-2', task: 'Add birthday-specific asset group', owner: 'media', dueWeeks: 2, status: 'pending' },
      { id: 'pmax-cup-3', task: 'New cupcake lifestyle photography for asset group', owner: 'production', dueWeeks: 3, status: 'pending' },
    ],
    benchmark: { outboundCTR: 2.59, roas: 3.93, cpm: 16.71, frequency: 1.0, budget: 'CA$37/day (~CA$1,110/mo)' },
    monthlyBudget: 'CA$1,110/mo (CA$37/day)',
    notes: 'Limited by Target — campaign is constrained. CTR 2.59% is strong. ROAS 3.93x — consider raising budget or relaxing tROAS.',
    seasonalColor: '#D97706',
    emoji: '',
    quarter: 1,
    month: 1,
    endMonth: 12,
    year: 2026,
    dataInsight: 'Apr 1–7: 11,472 impressions | 297 clicks | 2.59% CTR | 5.5 conversions | ROAS 3.93x | 23% of Google budget allocation — Limited by Target ROAS',
  },
  {
    id: 'ev-cookie-cakes-gta',
    name: 'PMax | Cookie Cakes | GTA',
    type: 'evergreen',
    status: 'active',
    priority: 'medium',
    channel: 'google',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    products: ['cookie-cakes'],
    productLabels: ['Cookie Cakes', 'Custom Cookie Cakes'],
    platforms: ['Google Performance Max'],
    goal: 'Drive cookie cake sales in GTA — Max Conversion Value. 96% products excluded — needs product feed fix.',
    targetAudience: 'GTA residents, birthday celebrators, event planners',
    location: 'GTA',
    adCopy: '"The ultimate birthday cookie cake." / "Custom cookie cakes — same day GTA delivery."',
    creativeIdeas: 'Cookie cake product shots, birthday occasion creative, custom order messaging',
    assets: ['Cookie cake photography', 'Custom order creative', 'Google asset group images'],
    productionTasks: [
      { id: 'pmax-cc-1', task: 'Fix product feed — 96% products excluded', owner: 'media', dueWeeks: 1, status: 'pending' },
      { id: 'pmax-cc-2', task: 'New cookie cake photography', owner: 'production', dueWeeks: 3, status: 'pending' },
      { id: 'pmax-cc-3', task: 'Review budget — currently CA$10/day (limited)', owner: 'media', dueWeeks: 1, status: 'pending' },
    ],
    benchmark: { outboundCTR: 1.76, roas: 4.19, cpm: 10.61, frequency: 1.0, budget: 'CA$10/day (~CA$300/mo)' },
    monthlyBudget: 'CA$300/mo (CA$10/day)',
    notes: '96% products excluded from campaign — critical fix needed. ROAS 4.19x is solid but volume is low due to budget cap.',
    seasonalColor: '#7B5C3A',
    emoji: '',
    quarter: 1,
    month: 1,
    endMonth: 12,
    year: 2026,
    dataInsight: 'Apr 1–7: 4,259 impressions | 75 clicks | 1.76% CTR | 2.5 conversions | ROAS 4.19x | 7% of Google budget — Limited by Budget, strong ROAS potential',
  },
  {
    id: 'ev-search-brand-gta',
    name: 'Search | Brand | GTA',
    type: 'evergreen',
    status: 'active',
    priority: 'high',
    channel: 'google',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    products: ['all'],
    productLabels: ['All Products — Brand Terms'],
    platforms: ['Google Search'],
    goal: 'Capture branded search intent — "Sweet Flour", "Sweet Flour cookies", "Sweet Flour Toronto". Protect brand traffic.',
    targetAudience: 'Existing customers, brand-aware searchers in GTA',
    location: 'GTA',
    adCopy: '"Sweet Flour — Fresh-Baked Cookies & Cupcakes. Same Day GTA Delivery."',
    creativeIdeas: 'Brand-focused headlines, sitelink extensions, promotion extensions',
    assets: ['Brand headlines', 'Sitelinks', 'Callout extensions', 'Promotion extensions'],
    productionTasks: [
      { id: 'brand-1', task: 'Fix "Ad strength is poor" — add more headlines/descriptions', owner: 'media', dueWeeks: 1, status: 'in-progress' },
      { id: 'brand-2', task: 'Add seasonal promotion extensions', owner: 'media', dueWeeks: 2, status: 'pending' },
      { id: 'brand-3', task: 'Review sitelinks — update for current promotions', owner: 'media', dueWeeks: 1, status: 'pending' },
    ],
    benchmark: { outboundCTR: 27.70, roas: 0.86, cpm: 367.16, frequency: 1.0, budget: 'CA$15.54/day (~CA$466/mo)' },
    monthlyBudget: 'CA$466/mo (CA$15.54/day)',
    notes: 'Brand campaign — 27.70% CTR is excellent (brand intent). ROAS 0.86 is expected for brand — measures incrementality, not direct ROAS. Ad strength is poor — fix urgently.',
    seasonalColor: '#3D8B5E',
    emoji: '',
    quarter: 1,
    month: 1,
    endMonth: 12,
    year: 2026,
    dataInsight: 'Apr 1–7: 278 impressions | 77 clicks | 27.70% CTR (brand intent) | 2 conversions | 26% of Google budget — Brand protection campaign, assists all other campaigns',
  },
  {
    id: 'ev-demand-gen-remarketing',
    name: 'Demand Gen | Remarketing | Canada',
    type: 'remarketing',
    status: 'active',
    priority: 'medium',
    channel: 'google',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    products: ['all'],
    productLabels: ['All Products — Dynamic Remarketing'],
    platforms: ['Google Demand Gen'],
    goal: 'Re-engage website visitors and past customers across Google\'s discovery surfaces (YouTube, Gmail, Discover)',
    targetAudience: 'Website visitors last 30 days, past purchasers, ATC abandoners',
    location: 'Canada',
    adCopy: '"Still craving something sweet? Your order is waiting." / "Fresh-baked and ready for you."',
    creativeIdeas: 'Dynamic product ads, personalized imagery, urgency messaging',
    assets: ['Dynamic product catalog', 'Remarketing creative templates', 'Urgency copy variants'],
    productionTasks: [
      { id: 'dg-1', task: 'Fix disapproved ads — review policy violations', owner: 'media', dueWeeks: 1, status: 'in-progress' },
      { id: 'dg-2', task: 'Create new Demand Gen creative set (image + video)', owner: 'design', dueWeeks: 2, status: 'pending' },
      { id: 'dg-3', task: 'Expand audience — add YouTube viewers segment', owner: 'media', dueWeeks: 2, status: 'pending' },
    ],
    benchmark: { outboundCTR: 2.75, roas: 0, cpm: 5.29, frequency: 1.0, budget: 'CA$2.73/day (~CA$82/mo)' },
    monthlyBudget: 'CA$82/mo (CA$2.73/day)',
    notes: 'Some ads disapproved + limited by policy. 0 conversions tracked — likely attribution issue. Very low budget. Consider increasing to CA$10–15/day.',
    seasonalColor: '#6B46C1',
    emoji: '',
    quarter: 1,
    month: 1,
    endMonth: 12,
    year: 2026,
    dataInsight: 'Apr 1–7: 4,901 impressions | 135 clicks | 2.75% CTR | 0 tracked conversions | 7% of Google budget — Some ads disapproved, remarketing audience building',
  },
  {
    id: 'ev-meta-cupcakes',
    name: 'Meta | Conversions | Cupcakes',
    type: 'evergreen',
    status: 'active',
    priority: 'high',
    channel: 'meta',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    products: ['cupcakes'],
    productLabels: ['Cupcakes', 'Cupcake Gift Boxes'],
    platforms: ['Meta (Facebook + Instagram)'],
    goal: 'Drive cupcake purchases via Meta Conversions campaign — website purchase objective',
    targetAudience: 'GTA + Canada women 25–54, birthday gift-givers, celebration occasions',
    location: 'GTA + Canada',
    adCopy: '"Celebrate with fresh-baked cupcakes." / "Same day Toronto delivery — order by 1pm."',
    creativeIdeas: 'Cupcake variety reels, birthday occasion UGC, slideshow video',
    assets: ['Cupcake Slideshow Video (top performer)', 'UGC voice-over creative', 'Static product images', 'Reels'],
    productionTasks: [
      { id: 'meta-cup-1', task: 'Produce new UGC voice-over cupcake video', owner: 'production', dueWeeks: 2, status: 'pending' },
      { id: 'meta-cup-2', task: 'Refresh slideshow video with new product shots', owner: 'design', dueWeeks: 3, status: 'pending' },
      { id: 'meta-cup-3', task: 'Test new ad copy angle: "Same day delivery"', owner: 'media', dueWeeks: 1, status: 'pending' },
    ],
    benchmark: { outboundCTR: 1.13, roas: 5.21, cpm: 16.36, frequency: 1.62, budget: 'CA$7.80/day avg (~CA$234/mo)' },
    monthlyBudget: 'CA$234/mo (CA$7.80/day avg)',
    notes: 'ROAS 5.21x in Apr 1–7. Cupcakes Slideshow Video is top performer historically. UGC voice-over achieved 1.78% Outbound CTR — scale this format.',
    seasonalColor: '#E91E8C',
    emoji: '',
    quarter: 1,
    month: 1,
    endMonth: 12,
    year: 2026,
    dataInsight: 'Apr 1–7: 2 purchases | ROAS 5.21x | Reach 2,890 | 22% of Meta budget allocation — Cupcakes prospecting',
  },
  {
    id: 'ev-meta-cookies',
    name: 'Meta | Conversions | Cookies',
    type: 'evergreen',
    status: 'active',
    priority: 'high',
    channel: 'meta',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    products: ['cookies', 'gift-boxes'],
    productLabels: ['Cookies', 'Cookie Gift Boxes', 'Cookie Cakes'],
    platforms: ['Meta (Facebook + Instagram)'],
    goal: 'Drive cookie and gift box purchases via Meta Conversions — website purchase objective',
    targetAudience: 'GTA + Canada women 25–54, gift-givers, corporate buyers',
    location: 'GTA + Canada',
    adCopy: '"The perfect gift, baked fresh today." / "Make any day sweeter with Sweet Flour cookies."',
    creativeIdeas: 'Cookie variety reels, gift box unboxing, UGC testimonials, seasonal creative',
    assets: ['Cookie Slideshow Video', 'Gift box lifestyle photography', 'UGC voice-over', 'Static product images'],
    productionTasks: [
      { id: 'meta-ck-1', task: 'Produce new UGC cookie unboxing video', owner: 'production', dueWeeks: 2, status: 'pending' },
      { id: 'meta-ck-2', task: 'Create gift box lifestyle photography set', owner: 'production', dueWeeks: 3, status: 'pending' },
      { id: 'meta-ck-3', task: 'Test carousel format for cookie variety', owner: 'media', dueWeeks: 1, status: 'pending' },
      { id: 'meta-ck-4', task: 'A/B test: product-focused vs. occasion-focused copy', owner: 'media', dueWeeks: 2, status: 'pending' },
    ],
    benchmark: { outboundCTR: 1.13, roas: 2.26, cpm: 16.36, frequency: 1.62, budget: 'CA$28.37/day avg (~CA$851/mo)' },
    monthlyBudget: 'CA$851/mo (CA$28.37/day avg)',
    notes: 'Top Meta campaign by spend. ROAS 2.26x in Apr 1–7 — below account avg 11.2x. Creative refresh needed. UGC format historically outperforms static.',
    seasonalColor: '#C8813A',
    emoji: '',
    quarter: 1,
    month: 1,
    endMonth: 12,
    year: 2026,
    dataInsight: 'Apr 1–7: 7 purchases | ROAS 2.26x | Reach 8,420 | 78% of Meta budget allocation — Cookies prospecting, creative refresh recommended',
  },
  // Meta | Conversions | Seasonal Promos is the container campaign used internally for seasonal activations.
  // It is intentionally excluded from the roadmap display — each seasonal campaign is tracked individually below.
  // ─────────────────────────────────────────────
  // Q1 — JAN / FEB / MAR
  // ─────────────────────────────────────────────
  {
    id: 'q1-valentine',
    name: 'Sweet Love — Valentine\'s Day',
    type: 'seasonal',
    status: 'planned',
    priority: 'high',
    channel: 'both',
    startDate: '2026-01-26',
    endDate: '2026-02-14',
    products: ['cookies', 'cupcakes', 'gift-boxes'],
    productLabels: ['Monogram Cookies', 'Gift Boxes', 'Cupcakes'],
    platforms: ['Meta (Facebook + Instagram)', 'Google PMax'],
    goal: 'Drive Valentine\'s gifting purchases — highest ROAS seasonal window (48x historically)',
    targetAudience: 'GTA + Canada couples, gift-givers, romantics 25–45',
    location: 'GTA + Canada',
    adCopy: '"Show love with cookies this Valentine\'s." / "The sweetest Valentine\'s gift — baked fresh."',
    creativeIdeas: 'Valentine\'s newsletter, carousel of heart-shaped cookies, monogram cookie showcase',
    assets: ['Valentine\'s product photography', 'Heart-shaped cookie creative', 'Monogram cookie showcase', 'Valentine\'s carousel'],
    productionTasks: [
      { id: 'val-1', task: 'Valentine\'s product photography session', owner: 'production', dueWeeks: 3, status: 'pending' },
      { id: 'val-2', task: 'Design Valentine\'s ad creative set (static + video)', owner: 'design', dueWeeks: 2, status: 'pending' },
      { id: 'val-3', task: 'Set up Valentine\'s campaign in Meta + Google', owner: 'media', dueWeeks: 1, status: 'pending' },
      { id: 'val-4', task: 'Client approval on Valentine\'s creative', owner: 'client', dueWeeks: 2, status: 'pending' },
    ],
    benchmark: { outboundCTR: 1.74, roas: 48, cpm: 16, frequency: 2.5, budget: 'CAD $200–300' },
    monthlyBudget: 'CAD $200–300',
    notes: 'Highest ROAS seasonal window in account history (48x). Start campaign Jan 26 — 2.5 weeks lead time. Valentine\'s newsletter + carousel historically strong.',
    seasonalColor: '#E53E3E',
    emoji: '',
    quarter: 1,
    month: 1,
    endMonth: 2,
    year: 2026,
    dataInsight: 'Historical Valentine\'s ROAS: 48x | Outbound CTR: 1.74% | Top format: Carousel + Newsletter',
  },
  {
    id: 'q1-spring-sweetness',
    name: 'Spring Sweetness — Easter 2026',
    type: 'seasonal',
    status: 'in-production',
    priority: 'high',
    channel: 'both',
    startDate: '2026-03-10',
    endDate: '2026-04-20',
    products: ['cupcakes', 'cookie-boxes'],
    productLabels: ['Easter Cupcakes', 'Cookie Boxes', 'Spring Treats'],
    platforms: ['Meta (Facebook + Instagram)', 'Google PMax'],
    goal: 'Drive Easter and spring gifting purchases — cookie boxes, Easter cupcakes',
    targetAudience: 'GTA + Canada families, gift-givers, spring event planners',
    location: 'GTA + Canada',
    adCopy: '"Make Easter sweeter with fresh-baked treats." / "Spring into Sweet Flour."',
    creativeIdeas: 'Easter cupcakes, spring cookie boxes, pastel product photography, spring lifestyle',
    assets: ['Easter product photography', 'Spring lifestyle shots', 'Pastel-themed creative', 'Easter carousel'],
    productionTasks: [
      { id: 'spring-1', task: 'Easter product photography session', owner: 'production', dueWeeks: 1, status: 'in-progress' },
      { id: 'spring-2', task: 'Design Easter/Spring ad creative set', owner: 'design', dueWeeks: 1, status: 'in-progress' },
      { id: 'spring-3', task: 'Set up Easter campaign in Meta + Google', owner: 'media', dueWeeks: 1, status: 'pending' },
      { id: 'spring-4', task: 'Client approval on Easter creative', owner: 'client', dueWeeks: 1, status: 'pending' },
    ],
    benchmark: { outboundCTR: 1.2, roas: 8, cpm: 18, frequency: 2.0, budget: 'CAD $200–300' },
    monthlyBudget: 'CAD $200–300',
    notes: 'Easter 2026 is Apr 5 — campaign should launch Mar 10. In production now. CPM is high in Apr (Q2 peak) — start early.',
    seasonalColor: '#68D391',
    emoji: '',
    quarter: 1,
    month: 3,
    endMonth: 4,
    year: 2026,
    dataInsight: 'Spring/Easter historically: Outbound CTR 1.2% | ROAS 8x | CPM spikes in Apr — launch early',
  },
  {
    id: 'q1-employee-appreciation',
    name: 'Employee Appreciation Day 2026',
    type: 'seasonal',
    status: 'planned',
    priority: 'medium',
    channel: 'both',
    startDate: '2026-02-21',
    endDate: '2026-03-06',
    products: ['corporate', 'gift-boxes'],
    productLabels: ['Corporate Boxes', 'Gift Boxes', 'Custom Orders'],
    platforms: ['Meta (Facebook + Instagram)', 'Google', 'LinkedIn'],
    goal: 'Target HR managers and business owners for Employee Appreciation Day (Mar 6, 2026) corporate gifting',
    targetAudience: 'HR managers, business owners, executive assistants, GTA companies',
    location: 'GTA + Canada',
    adCopy: '"Say thank you with something sweet." / "Make your team feel appreciated with Sweet Flour."',
    creativeIdeas: 'Corporate gifting assets, branded box photography, B2B messaging',
    assets: ['Corporate gifting creative', 'Branded box photos', 'B2B ad copy', 'LinkedIn creative'],
    productionTasks: [
      { id: 'emp-1', task: 'Design corporate gifting ad creative', owner: 'design', dueWeeks: 3, status: 'pending' },
      { id: 'emp-2', task: 'Set up LinkedIn test campaign (CA$100)', owner: 'media', dueWeeks: 2, status: 'pending' },
      { id: 'emp-3', task: 'Client approval on B2B messaging', owner: 'client', dueWeeks: 2, status: 'pending' },
    ],
    benchmark: { outboundCTR: 0.7, roas: 5, cpm: 20, frequency: 2.0, budget: 'CAD $100–200' },
    monthlyBudget: 'CAD $100–200',
    notes: 'Small spend, high intent B2B audience. LinkedIn test recommended — CA$100 budget. Corporate gifting CPM is higher but purchase value is much larger.',
    seasonalColor: '#4A5568',
    emoji: '',
    quarter: 1,
    month: 2,
    endMonth: 3,
    year: 2026,
    dataInsight: 'Corporate gifting: Outbound CTR 0.7% target | ROAS 5x | High AOV — corporate orders avg 3–5x individual orders',
  },
  // ─────────────────────────────────────────────
  // Q2 — APR / MAY / JUN
  // ─────────────────────────────────────────────
  {
    id: 'q2-admin-day',
    name: 'Admin Pro Gifting — Admin Day',
    type: 'seasonal',
    status: 'active',
    priority: 'medium',
    channel: 'both',
    startDate: '2026-04-06',
    endDate: '2026-04-22',
    products: ['gift-boxes', 'cookies'],
    productLabels: ['Gift Boxes', 'Cookie Boxes', 'Custom Orders'],
    platforms: ['Google', 'Meta'],
    goal: 'Target businesses for Administrative Professionals Day (Apr 22, 2026) — small spend, high intent',
    targetAudience: 'Business owners, managers, GTA companies',
    location: 'GTA',
    adCopy: '"Thank your admin with something sweet." / "The best Admin Day gift — custom cookies."',
    creativeIdeas: 'Corporate gifting assets, thank-you messaging, small batch custom orders',
    assets: ['Corporate gifting creative', 'Thank-you messaging', 'Custom order photography'],
    productionTasks: [
      { id: 'admin-1', task: 'Adapt corporate gifting creative for Admin Day', owner: 'design', dueWeeks: 1, status: 'pending' },
      { id: 'admin-2', task: 'Set up Admin Day campaign', owner: 'media', dueWeeks: 1, status: 'pending' },
    ],
    benchmark: { outboundCTR: 0.8, roas: 4, cpm: 20, frequency: 2.0, budget: 'CAD $100–150' },
    monthlyBudget: 'CAD $100–150',
    notes: 'Small spend, high intent. Admin Day is Apr 22. LinkedIn CPM is high on LinkedIn — use Meta + Google for this one.',
    seasonalColor: '#718096',
    emoji: '',
    quarter: 2,
    month: 4,
    endMonth: 4,
    year: 2026,
    ksNotes: 'Small spend, high intent. CPM is high on LinkedIn — use Meta + Google for this one.',
  },
  {
    id: 'q2-mothers-day',
    name: 'Sweet Moments for Mom — Mother\'s Day',
    type: 'seasonal',
    status: 'in-production',
    priority: 'high',
    channel: 'both',
    startDate: '2026-04-27',
    endDate: '2026-05-10',
    products: ['gift-boxes', 'cupcakes', 'cookies'],
    productLabels: ['Gift Boxes', 'Monogram Cookies', 'Cupcakes'],
    platforms: ['Meta (Facebook + Instagram)', 'Google PMax'],
    goal: 'Drive Mother\'s Day gifting purchases — second highest seasonal revenue window',
    targetAudience: 'GTA + Canada adults 25–45, children buying for mothers, families',
    location: 'GTA + Canada',
    adCopy: '"Make Mom\'s day extra sweet." / "The best Mother\'s Day gift — baked with love."',
    creativeIdeas: 'Mother\'s Day newsletter, monogram cookie showcase, gift box lifestyle',
    assets: ['Mother\'s Day product photography', 'Monogram cookie creative', 'Gift box lifestyle shots', 'Mother\'s Day carousel'],
    productionTasks: [
      { id: 'mom-1', task: 'Mother\'s Day product photography session', owner: 'production', dueWeeks: 2, status: 'in-progress' },
      { id: 'mom-2', task: 'Design Mother\'s Day ad creative set', owner: 'design', dueWeeks: 2, status: 'pending' },
      { id: 'mom-3', task: 'Set up Mother\'s Day campaign in Meta + Google', owner: 'media', dueWeeks: 1, status: 'pending' },
      { id: 'mom-4', task: 'Client approval on Mother\'s Day creative', owner: 'client', dueWeeks: 2, status: 'pending' },
    ],
    benchmark: { outboundCTR: 1.5, roas: 12, cpm: 18, frequency: 2.5, budget: 'CAD $300–500' },
    monthlyBudget: 'CAD $300–500',
    notes: 'Start early — Mother\'s Day is May 10. Launch Apr 27. Newsletter + carousel historically strong. Same-day delivery messaging is key differentiator.',
    seasonalColor: '#ED64A6',
    emoji: '',
    quarter: 2,
    month: 4,
    endMonth: 5,
    year: 2026,
    dataInsight: 'Mother\'s Day historically: ROAS 12x | Outbound CTR 1.5% | Top format: Newsletter + Carousel',
  },
  {
    id: 'q2-graduation',
    name: 'Graduation + Teacher Gift',
    type: 'seasonal',
    status: 'in-production',
    priority: 'high',
    channel: 'both',
    startDate: '2026-04-27',
    endDate: '2026-06-25',
    products: ['grad-packs', 'cookie-cakes', 'teacher-gifts'],
    productLabels: ['Grad Packs', 'Cookie Cakes', 'Teacher Gift Sets', 'Custom Orders'],
    platforms: ['Meta (Facebook + Instagram)', 'Google PMax'],
    goal: 'Drive graduation gifting and teacher appreciation orders — grad packs, cookie cakes, teacher gift sets. Client-requested Apr 27 start, running until Jun 25.',
    targetAudience: 'GTA families, parents of graduates, university graduation events, teachers and school staff gift-givers',
    location: 'GTA + Canada',
    adCopy: '"Celebrate their big day with Sweet Flour." / "The perfect grad gift, baked fresh." / "Say thank you with something sweet — teacher gift sets available."',
    creativeIdeas: 'Grad collection photos from sweetflour.ca, teacher gift pics (provided by Kristen Apr 8), AI-generated celebration imagery, cookie cake custom order messaging',
    assets: ['Grad collection photos (live on sweetflour.ca)', 'Teacher gift photos (provided by client Apr 8)', 'AI-generated grad celebration imagery', 'Cookie cake custom order creative'],
    productionTasks: [
      { id: 'grad-1', task: 'Campaign setup — Meta + Google (due Apr 17, assigned: Daniel G. + Muhammed R.)', owner: 'media', dueWeeks: 1, status: 'in-progress' },
      { id: 'grad-2', task: 'Design grad + teacher gift ad creative set', owner: 'design', dueWeeks: 1, status: 'in-progress' },
      { id: 'grad-3', task: 'Source grad collection photos from sweetflour.ca + teacher gift folder', owner: 'production', dueWeeks: 1, status: 'in-progress' },
      { id: 'grad-4', task: 'Client approval on creative before launch (notify Kim G. + Kristen)', owner: 'client', dueWeeks: 1, status: 'pending' },
      { id: 'grad-5', task: 'Launch campaigns on Apr 27', owner: 'media', dueWeeks: 2, status: 'pending' },
    ],
    benchmark: { outboundCTR: 1.0, roas: 7, cpm: 18, frequency: 2.0, budget: 'CAD $300–500' },
    monthlyBudget: 'CAD $300–500/mo',
    notes: 'Client (Kristen) requested Apr 27 start, run until Jun 25. Grad collection live on sweetflour.ca — use those photos or AI-generated pics. Teacher gift pics also provided by Kristen Apr 8. Task assigned to Daniel G. + Muhammed R., due Apr 17. Notify Kim G. + Kristen when done.',
    seasonalColor: '#9F7AEA',
    emoji: '',
    quarter: 2,
    month: 4,
    endMonth: 6,
    year: 2026,
    dataInsight: 'Client-requested campaign (Kristen, Apr 8). Grad collection photos live on sweetflour.ca. Teacher gift angle added. Task due Apr 17.',
    ksNotes: 'Start Apr 27, run until Jun 25. Use grad collection photos from sweetflour.ca or AI-generated. Teacher gift pics available. Task due Apr 17 — notify Kim G. + Kristen when done.',
  },
  {
    id: 'q2-fathers-day',
    name: 'Dad Deserves It — Father\'s Day',
    type: 'seasonal',
    status: 'planned',
    priority: 'medium',
    channel: 'both',
    startDate: '2026-06-01',
    endDate: '2026-06-21',
    products: ['cookie-boxes', 'gift-bundles'],
    productLabels: ['Cookie Boxes', 'Gift Bundles', 'Custom Orders'],
    platforms: ['Meta (Facebook + Instagram)', 'Google PMax'],
    goal: 'Drive Father\'s Day gifting purchases — cookie boxes, gift bundles',
    targetAudience: 'GTA + Canada adults 25–45, children buying for fathers, families',
    location: 'GTA + Canada',
    adCopy: '"Make Dad smile with Sweet Flour." / "The best Father\'s Day gift — baked fresh."',
    creativeIdeas: 'Father\'s Day newsletter, cookie box lifestyle, masculine-toned product shots',
    assets: ['Father\'s Day product photography', 'Cookie box lifestyle shots', 'Father\'s Day newsletter'],
    productionTasks: [
      { id: 'dad-1', task: 'Father\'s Day product photography', owner: 'production', dueWeeks: 5, status: 'pending' },
      { id: 'dad-2', task: 'Design Father\'s Day ad creative', owner: 'design', dueWeeks: 4, status: 'pending' },
      { id: 'dad-3', task: 'Set up Father\'s Day campaign', owner: 'media', dueWeeks: 3, status: 'pending' },
    ],
    benchmark: { outboundCTR: 1.0, roas: 8, cpm: 18, frequency: 2.0, budget: 'CAD $200' },
    monthlyBudget: 'CAD $200',
    notes: 'Father\'s Day is Jun 21. Newsletter historically strong. Masculine-toned creative performs better for this occasion.',
    seasonalColor: '#2D3748',
    emoji: '',
    quarter: 2,
    month: 6,
    endMonth: 6,
    year: 2026,
  },
  // ─────────────────────────────────────────────
  // Q3 — JUL / AUG / SEP
  // ─────────────────────────────────────────────
  {
    id: 'q3-wedding-summer',
    name: 'Wedding Season Focus',
    type: 'seasonal',
    status: 'planned',
    priority: 'high',
    channel: 'both',
    startDate: '2026-07-01',
    endDate: '2026-08-31',
    products: ['trays', 'desk-drops', 'wedding-orders'],
    productLabels: ['Trays', 'Desk Drops', 'Wedding Orders', 'DIY Kits'],
    platforms: ['Meta (Facebook + Instagram)', 'Google PMax'],
    goal: 'Capture wedding catering and gifting orders — summer wedding season peak',
    targetAudience: 'GTA brides, wedding planners, event coordinators, engaged couples',
    location: 'GTA',
    adCopy: '"Cookies for every celebration." / "Sweet Flour for your wedding day."',
    creativeIdeas: 'Wedding-styled product shots, elegant packaging, wedding planner testimonials',
    assets: ['Wedding-styled product photography', 'Elegant packaging shots', 'Wedding planner testimonials'],
    productionTasks: [
      { id: 'wed-1', task: 'Wedding product photography session', owner: 'production', dueWeeks: 8, status: 'pending' },
      { id: 'wed-2', task: 'Design wedding-focused ad creative', owner: 'design', dueWeeks: 7, status: 'pending' },
      { id: 'wed-3', task: 'Research wedding show opportunities in GTA', owner: 'client', dueWeeks: 6, status: 'pending' },
    ],
    benchmark: { outboundCTR: 1.0, roas: 8, cpm: 16, frequency: 2.0, budget: 'CAD $200–350' },
    monthlyBudget: 'CAD $200–350',
    notes: 'Big show opportunity in GTA. Wedding orders have very high AOV. Consider wedding show sponsorship alongside digital.',
    seasonalColor: '#F6E05E',
    emoji: '',
    quarter: 3,
    month: 7,
    endMonth: 8,
    year: 2026,
    ksNotes: 'Big show opportunity in GTA. Wedding orders have very high AOV.',
  },
  {
    id: 'q3-back-to-school',
    name: 'Back-to-School Sweetness',
    type: 'seasonal',
    status: 'planned',
    priority: 'medium',
    channel: 'both',
    startDate: '2026-09-01',
    endDate: '2026-09-30',
    products: ['snack-packs', 'baby-gifts'],
    productLabels: ['Snack Packs', 'Baby Gifts', 'Teacher Gifts'],
    platforms: ['Meta (Facebook + Instagram)', 'Google PMax'],
    goal: 'Drive back-to-school gifting — teacher gifts, snack packs, baby gifts',
    targetAudience: 'GTA parents, teachers, new parents',
    location: 'GTA',
    adCopy: '"Start the school year sweet." / "The perfect teacher gift — Sweet Flour cookies."',
    creativeIdeas: 'Back-to-school themed creative, teacher gift messaging, snack pack photography',
    assets: ['Back-to-school creative', 'Teacher gift messaging', 'Snack pack photography'],
    productionTasks: [
      { id: 'bts-1', task: 'Back-to-school creative production', owner: 'design', dueWeeks: 12, status: 'pending' },
      { id: 'bts-2', task: 'Set up back-to-school campaign', owner: 'media', dueWeeks: 11, status: 'pending' },
    ],
    benchmark: { outboundCTR: 1.0, roas: 6, cpm: 16, frequency: 2.0, budget: 'CAD $200–300' },
    monthlyBudget: 'CAD $200–300',
    notes: 'Sept and Oct are just getting started — back-to-school super relevant. Also consider teacher appreciation angle.',
    seasonalColor: '#F6AD55',
    emoji: '',
    quarter: 3,
    month: 9,
    endMonth: 9,
    year: 2026,
    ksNotes: 'Sept and Oct are just getting started — back-to-school super relevant.',
  },
  // ─────────────────────────────────────────────
  // Q4 — OCT / NOV / DEC
  // ─────────────────────────────────────────────
  {
    id: 'q4-thanksgiving',
    name: 'Grateful Gifting — Thanksgiving',
    type: 'seasonal',
    status: 'planned',
    priority: 'high',
    channel: 'both',
    startDate: '2026-09-15',
    endDate: '2026-10-12',
    products: ['gift-boxes', 'apple-cookies', 'signature-boxes'],
    productLabels: ['Signature Cookie Gift Box', 'Apple Cookies', 'Gift Boxes'],
    platforms: ['Meta (Facebook + Instagram)', 'Google PMax'],
    goal: 'Drive Thanksgiving gifting — small push, high intent. Canadian Thanksgiving Oct 12.',
    targetAudience: 'GTA + Canada families, corporate gifters, host gifts',
    location: 'GTA + Canada',
    adCopy: '"Share cookies, share gratitude." / "The perfect Thanksgiving host gift."',
    creativeIdeas: 'Re-use 2024 winners: Apple Poskie static, Thanksgiving Cookie Gift Box. Update with new product shots.',
    assets: ['Thanksgiving product photography', 'Apple cookie creative', 'Gratitude-themed messaging'],
    productionTasks: [
      { id: 'tg-1', task: 'Update Thanksgiving creative with 2026 products', owner: 'design', dueWeeks: 16, status: 'pending' },
      { id: 'tg-2', task: 'Set up Thanksgiving campaign', owner: 'media', dueWeeks: 15, status: 'pending' },
    ],
    benchmark: { outboundCTR: 1.2, roas: 10, cpm: 16, frequency: 2.0, budget: 'CAD $200–500' },
    monthlyBudget: 'CAD $200–500',
    notes: 'Smaller budget — high intent. Re-use 2024 winners (Apple Poskie static + Thanksgiving Cookie Gift Box). Start Sep 15.',
    seasonalColor: '#DD6B20',
    emoji: '',
    quarter: 4,
    month: 9,
    endMonth: 10,
    year: 2026,
    dataInsight: 'Re-use 2024 winners: Apple Poskie static + Thanksgiving Cookie Gift Box. Updated static mostly.',
  },
  {
    id: 'q4-halloween',
    name: 'Spooky Sweet 2026 — Halloween',
    type: 'seasonal',
    status: 'planned',
    priority: 'high',
    channel: 'both',
    startDate: '2026-10-01',
    endDate: '2026-10-31',
    products: ['cupcakes', 'ghost-cookies', 'cookie-boxes'],
    productLabels: ['Ghost Cookie Cupcakes', 'Spooky Cookie Box', 'Halloween Gift Boxes'],
    platforms: ['Meta (Facebook + Instagram)', 'Google PMax'],
    goal: 'Drive Halloween treat orders — spooky cookie boxes, ghost cupcakes, Halloween gift boxes',
    targetAudience: 'GTA families, parents, Halloween party planners',
    location: 'GTA + Canada',
    adCopy: '"Trick or treat — mostly treat." / "Spooky cookies for your Halloween celebration."',
    creativeIdeas: 'Re-use 2024 winners: Halloween Reels, Static Cookie Box. New: Spooky Cookie Box.',
    assets: ['Halloween product photography', 'Spooky-themed creative', 'Halloween Reels'],
    productionTasks: [
      { id: 'hal-1', task: 'Halloween product photography session', owner: 'production', dueWeeks: 18, status: 'pending' },
      { id: 'hal-2', task: 'Design Halloween ad creative set', owner: 'design', dueWeeks: 17, status: 'pending' },
      { id: 'hal-3', task: 'Set up Halloween campaign', owner: 'media', dueWeeks: 16, status: 'pending' },
    ],
    benchmark: { outboundCTR: 1.73, roas: 10, cpm: 16, frequency: 2.5, budget: 'CAD $200–500' },
    monthlyBudget: 'CAD $200–500',
    notes: 'Halloween Outbound CTR: 1.73% (strong). Re-use 2024 Halloween Reels + Static Cookie Box. Add new Spooky Cookie Box creative.',
    seasonalColor: '#ED8936',
    emoji: '',
    quarter: 4,
    month: 10,
    endMonth: 10,
    year: 2026,
    dataInsight: 'Halloween Outbound CTR: 1.73% | ROAS 10x | Top format: Reels + Static Cookie Box',
  },
  {
    id: 'q4-holiday',
    name: 'Holiday Cheer 2026 — Christmas + Holiday',
    type: 'seasonal',
    status: 'planned',
    priority: 'high',
    channel: 'both',
    startDate: '2026-11-03',
    endDate: '2026-12-19',
    products: ['gift-boxes', 'custom-cookies', 'corporate-orders'],
    productLabels: ['Gift Boxes', 'Custom Cookies', 'Corporate Orders'],
    platforms: ['Meta (Facebook + Instagram)', 'Google PMax'],
    goal: 'Peak holiday revenue — Christmas gifting, corporate orders, BFCM promotions. Highest spend window.',
    targetAudience: 'GTA + Canada gift-givers, corporate buyers, holiday shoppers',
    location: 'GTA + Canada',
    adCopy: '"Start the year with fresh-baked holiday cookies." / "The perfect holiday gift — baked fresh."',
    creativeIdeas: 'Holiday creative + promotion details (start date, % discount applicable to all products)',
    assets: ['Holiday product photography', 'BFCM promotion creative', 'Corporate gifting creative', 'Holiday video'],
    productionTasks: [
      { id: 'hol-1', task: 'Holiday product photography session', owner: 'production', dueWeeks: 20, status: 'pending' },
      { id: 'hol-2', task: 'Design BFCM promotion creative', owner: 'design', dueWeeks: 19, status: 'pending' },
      { id: 'hol-3', task: 'Design Holiday ad creative set (static + video)', owner: 'design', dueWeeks: 18, status: 'pending' },
      { id: 'hol-4', task: 'Set up Holiday + BFCM campaigns', owner: 'media', dueWeeks: 17, status: 'pending' },
      { id: 'hol-5', task: 'Client approval on Holiday promotion details', owner: 'client', dueWeeks: 18, status: 'pending' },
    ],
    benchmark: { outboundCTR: 2.04, roas: 21, cpm: 22, frequency: 3.0, budget: 'CAD $1,000–1,500' },
    monthlyBudget: 'CAD $1,000–1,500',
    notes: 'Highest ROAS window after Valentine\'s (21x). Outbound CTR 2.04% — best in account. Prog begins Oct. Budget increase justified. Include BFCM promotion details.',
    seasonalColor: '#C53030',
    emoji: '',
    quarter: 4,
    month: 11,
    endMonth: 12,
    year: 2026,
    dataInsight: 'Holiday/BFCM Outbound CTR: 2.04% (best in account) | ROAS 21x | Top format: Urgency copy + Promotion creative',
  },
];

export const productionDeadlines = [
  // April 2026 — Graduation + Teacher Gift (URGENT — task due Apr 17)
  { date: '2026-04-17', type: 'launch', event: 'Grad + Teacher Gift: Campaign setup due (Daniel G. + Muhammed R.)', campaign: 'q2-graduation' },
  { date: '2026-04-17', type: 'design', event: 'Grad + Teacher Gift: Ad creative set due', campaign: 'q2-graduation' },
  { date: '2026-04-20', type: 'production', event: 'Grad + Teacher Gift: Client approval (notify Kim G. + Kristen)', campaign: 'q2-graduation' },
  { date: '2026-04-27', type: 'launch', event: 'Grad + Teacher Gift: Campaign LAUNCH', campaign: 'q2-graduation' },
  // April–May 2026 — Mother's Day
  { date: '2026-04-10', type: 'production', event: "Mother's Day: Product photography due", campaign: 'q2-mothers-day' },
  { date: '2026-04-17', type: 'design', event: "Mother's Day: Ad creative design due", campaign: 'q2-mothers-day' },
  { date: '2026-04-24', type: 'launch', event: "Mother's Day: Campaign setup + client approval", campaign: 'q2-mothers-day' },
  { date: '2026-04-27', type: 'launch', event: "Mother's Day: Campaign LAUNCH", campaign: 'q2-mothers-day' },
  // May–June 2026 — Father's Day
  { date: '2026-05-15', type: 'production', event: "Father's Day: Product photography due", campaign: 'q2-fathers-day' },
  { date: '2026-05-22', type: 'design', event: "Father's Day: Ad creative design due", campaign: 'q2-fathers-day' },
  { date: '2026-06-01', type: 'launch', event: "Father's Day: Campaign setup + launch", campaign: 'q2-fathers-day' },
  // July–August 2026 — Wedding Season
  { date: '2026-06-15', type: 'production', event: 'Wedding Season: Product photography session', campaign: 'q3-wedding-summer' },
  { date: '2026-06-22', type: 'design', event: 'Wedding Season: Ad creative design due', campaign: 'q3-wedding-summer' },
  { date: '2026-07-01', type: 'launch', event: 'Wedding Season: Campaign LAUNCH', campaign: 'q3-wedding-summer' },
  // September 2026 — Back to School
  { date: '2026-08-17', type: 'design', event: 'Back-to-School: Creative production due', campaign: 'q3-back-to-school' },
  { date: '2026-09-01', type: 'launch', event: 'Back-to-School: Campaign LAUNCH', campaign: 'q3-back-to-school' },
  // September–October 2026 — Thanksgiving
  { date: '2026-08-31', type: 'design', event: 'Thanksgiving: Creative update due', campaign: 'q4-thanksgiving' },
  { date: '2026-09-15', type: 'launch', event: 'Thanksgiving: Campaign LAUNCH', campaign: 'q4-thanksgiving' },
  // October 2026 — Halloween
  { date: '2026-09-14', type: 'production', event: 'Halloween: Product photography session', campaign: 'q4-halloween' },
  { date: '2026-09-21', type: 'design', event: 'Halloween: Ad creative set due', campaign: 'q4-halloween' },
  { date: '2026-10-01', type: 'launch', event: 'Halloween: Campaign LAUNCH', campaign: 'q4-halloween' },
  // November–December 2026 — Holiday + BFCM
  { date: '2026-10-05', type: 'production', event: 'Holiday/BFCM: Product photography session', campaign: 'q4-holiday' },
  { date: '2026-10-12', type: 'design', event: 'Holiday/BFCM: BFCM promotion creative due', campaign: 'q4-holiday' },
  { date: '2026-10-19', type: 'design', event: 'Holiday/BFCM: Holiday ad creative set due', campaign: 'q4-holiday' },
  { date: '2026-10-26', type: 'launch', event: 'Holiday/BFCM: Campaign setup + client approval', campaign: 'q4-holiday' },
  { date: '2026-11-03', type: 'launch', event: 'Holiday/BFCM: Campaign LAUNCH', campaign: 'q4-holiday' },
];

// Convenience exports used by DashboardView and PerformanceView
export const allCampaigns = campaigns;

export const benchmarks = {
  outboundCTR: 1.13,
  roas: 11.2,
  cpm: 16.36,
  frequency: 1.62,
};

export const googleCampaigns = [
  { name: 'PMax | Cookies | Canada', type: 'Performance Max', budgetShare: 40, ctr: 1.73, conversions: 12.0, roas: 5.20, status: 'Eligible' },
  { name: 'PMax | Cupcakes | GTA', type: 'Performance Max', budgetShare: 23, ctr: 2.59, conversions: 5.5, roas: 3.93, status: 'Limited by Target' },
  { name: 'PMax | Cookie Cakes | GTA', type: 'Performance Max', budgetShare: 7, ctr: 1.76, conversions: 2.5, roas: 4.19, status: 'Limited by Budget' },
  { name: 'Search | Brand | GTA', type: 'Search', budgetShare: 26, ctr: 27.70, conversions: 2.0, roas: 0.86, status: 'Eligible' },
  { name: 'Demand Gen | Remarketing | Canada', type: 'Demand Gen', budgetShare: 7, ctr: 2.75, conversions: 0.0, roas: 0.00, status: 'Limited by Budget' },
];

export const metaCampaigns = [
  { name: 'Sweet Flour | Conversions | Cupcakes Campaign', results: 2, reach: 2890, budgetShare: 22, roas: 5.21 },
  { name: 'Sweet Flour | Conversions | Cookies Campaign', results: 3, reach: 8420, budgetShare: 78, roas: 2.26 },
];
